### ISSUE TITLE
Headphone base noise level is very high

### ISSUE THREAD

**Issue by gaborkr** [advancingu/XPS13Linux#11] opened 2015-05-11 09:44 UTC
On kernel 3.19, the soundcard has a very high level of base noise on the headphone output - much higher than anything I can compare it to. The noise is gone if I mute the output. I can play with alsamixer and change the microphone levels - if I mute the mic, the noise becomes even worse, with added intermittent chirping. The noise is the same regardless of the headphone type (headphone only / headset with mic).

[This issue](http://en.community.dell.com/support-forums/software-os/f/3525/t/19563481) looks similar - maybe it can be fixed with a different configuration of the sound card. ~~However, the background noise is present in Windows too.~~ Correction: I can no longer detect the extra noise in Windows.

**Comment by advancingu** [comment] 2015-05-11 10:55
Is this with the 2015 edition?

**Comment by gaborkr** [comment] 2015-05-11 10:56
Yes, of course.

**Comment by advancingu** [comment] 2015-05-11 11:03
I don't have this on my machine at all with stock Ubuntu 15.04 and BIOS A03.

**Comment by dchambers** [comment] 2015-05-12 20:44
Could we add a `Fixed in 15.04` label if it's definitely fixed in that release, so others looking to see the state of play with this laptop can more quickly see how things stand?

**Comment by advancingu** [comment] 2015-05-12 21:57
@butabeka Which distribution and release is this occurring on?

**Comment by gaborkr** [comment] 2015-05-13 08:44
Ubuntu 15.04 (3.19.0-16) with PulseAudio installed. BIOS A03.
Just to make sure that this is a Linux problem, I rebooted to Windows (2x cold boot) and started playing "Dancing with the Moonlit Knight", which starts with Peter Gabriel singing, without any other instruments in the background. It played fine.
Then rebooted to Linux (2x cold boot), started playing the same song. First there was no output, I had to open the volume controls and click on some tabs, then suddenly the sound was unmuted, and Peter Gabriel was singing again, with a very noticeable white noise in the background.
I played around alsamixer and pulseaudio a lot, believe me, tried to change all possible mixer settings, but no luck.

**Comment by advancingu** [comment] 2015-05-13 08:47
Are these headphones with an integrated microphone? Which type of connector/plug do your headphones use?

**Comment by gaborkr** [comment] 2015-05-13 08:57
Both headphone (3-way jack connector) and headset (with a mic, 4-way connector) exhibit this behaviour. If I stop playing the song the noise remains, until I mute the output altogether (so it's not a player error - eg. wrong decoding of mp3 or too much amplification).
I also have an external USB DAC which works just fine.

**Comment by gaborkr** [comment] 2015-05-14 06:52
OK, this is funny: I think I found the fix. [This is it.](http://xps13-9333.appspot.com/#background_noise): [Download and run this script](http://xps13-9333.appspot.com/root/usr/local/bin/white_noise_fix.py) (the alsa-tools package needs to be installed).

The funny part is that it is a fix for the previous version of the XPS 13... Also, it is for pre-3.16 kernels - I'm on 3.19... Now I'm scratching my head...

**Comment by advancingu** [comment] 2015-05-14 07:14
Thanks for updating with a link to the fix. Good to hear you were able to resolve the issue. I'll close this for now.

**Closed as completed by advancingu** 2015-05-14 07:14 UTC

**Comment by dchambers** [comment] 2015-05-14 07:21
Good work @butabeka. Out of interest, did you upgrade to 15.04 or are you a fresh install?

**Comment by gaborkr** [comment] 2015-05-14 08:59
@dchambers I experimented with Fedora 21 (beta?) and Ubuntu 14.04/14.10 about a month ago, then installed 15.04 as soon as it got released. I used Windows in the meantime.

**Comment by dchambers** [comment] 2015-05-14 09:01
Right, but was it a fresh install rather an a `dist upgrade` from an earlier installation?

**Comment by gaborkr** [comment] 2015-05-14 09:37
Fresh install. I also get the same behaviour when running from a Live USB.

**Comment by soren121** [comment] 2015-05-17 21:13
For what it's worth, I have the 2015 XPS 13 (9343) running Arch with kernel 4.0, and the above Python script fixes my audio. The white noise is greatly reduced and it removes the annoying oscillating noise.

I noticed that the [kernel patch](https://git.kernel.org/cgit/linux/kernel/git/tiwai/sound.git/commit/sound/pci/hda/patch_realtek.c?id=5e6db6699b7651f02f4b7cc6a86f5b3d9359d636) for the 9333 model is a quirk that specifically targets the ALC668 sound card used in that machine. Perhaps applying the same fix for the 9343's ALC288 chipset would work as well. I'm going to experiment with that.

**Comment by webloem** [comment] 2015-06-15 12:24
I have the same problem. I ran the script, it (mostly) fixes the problem. After reboot the problem is back though, so will need to run this script on boot. A more permanent fix would be nice.

**Comment by gaborkr** [comment] 2015-06-15 14:30
I started using powertop, and unfortunately, a side effect of turning the audio card on and off for power saving results in the noise coming back every time. This is really annoying...

**Comment by soren121** [comment] 2015-06-15 16:55
There's a patch available here: https://bugzilla.kernel.org/show_bug.cgi?id=99851

It fixed the noise issue for me, but I'd like for a few other people to test it as well to ensure it's resolved.

**Comment by soren121** [comment] 2015-06-15 19:04
Update: the patch is now queued for 4.1. [Here's the commit.](https://git.kernel.org/cgit/linux/kernel/git/tiwai/sound.git/commit/?h=for-linus&id=82d6d8a4034a7480d582791763c89c328c2a8f0c)

**Comment by gaborkr** [comment] 2015-06-16 08:05
This is great news and thank you for being proactive - I should have reported this a long time ago. I'm still on 3.19, waiting for 4.1 to be released (I hope it works with the XPS13 reasonably well now).

**Comment by soren121** [comment] 2015-06-16 08:43
Good news: it does. I've been running 4.1-rc6 for a while now with almost no problems. A bunch of driver patches made it in that fix audio, touchpad, and WiFi issues. The only outstanding problem is the H-sync loss when switching TTYs...it was fixed a few days ago but I don't think it'll be merged until the 4.2 window opens. There's a workaround, though-- check the Arch Wiki.

I've been having some trouble lately with suspend-on-lid-close and some oddities with right-clicking, but I'm not certain those are kernel-related. I need to look into those more.

-----Original Message-----

**Comment by dchambers** [comment] 2015-06-16 10:09
>  A bunch of driver patches made it in that fix audio, touchpad, and WiFi issues.

Hi @soren121, are you able to provide more details regarding the touchpad and WiFI fixes in 4.1 that affect the XPS 13? Do you know if there's anything for the palm detection bug for example?

**Comment by soren121** [comment] 2015-06-16 15:32
Two notable bugs that were fixed:

https://bugs.freedesktop.org/show_bug.cgi?id=88903
https://bugzilla.kernel.org/show_bug.cgi?id=95941

EDIT: Regarding palm detection, this looks promising: https://bugzilla.kernel.org/show_bug.cgi?id=77161#c20

**Comment by dchambers** [comment] 2015-06-16 15:43
Thanks @soren121, this is really helpful information. It's great to see how the community are helping to keep Dell's promises regarding Linux compatibility.

**Comment by gaborkr** [comment] 2015-06-22 13:56
And the fix made it into 4.1, in the last minute:
http://lkml.iu.edu/hypermail/linux/kernel/1506.2/04143.html

Takashi Iwai (3):
(...)
ALSA: hda - Fix noisy outputs on Dell XPS13 (2015 model)

**Comment by gaborkr** [comment] 2015-06-23 10:14
4.1 status: microphone input is gone silent.  @soren121 do you have the same problem?

(Removed: ~~Also, with a headset (with a 4-way jack) the left output channel is much quieter than the right channel. Interestingly, stereo is fine when a normal headphone is plugged in.~~ -> This might have been due to a broken headset...)

**Comment by soren121** [comment] 2015-06-25 01:59
Yes, I have the same problem. I'll take the blame for it, I was the one who tested the patch...

Someone else has reported the regression upstream on the same bug report, so hopefully we'll get another patch soon.

**Comment by gaborkr** [comment] 2015-07-24 10:14
FYI 4.1.3 at last seems to have the mic patch applied (https://www.kernel.org/pub/linux/kernel/v4.x/ChangeLog-4.1.3 - "ALSA: hda - restore the MIC FIXUP for some Dell machines").

So if you want sound fully working but do not want to patch and compile a kernel for yourself you can now fetch 4.1.3 binary (or, if you are feeling lucky, any of the 4.2 RC versions...). 4.1 has been stable and problem free for me so far.
